### ISSUE TITLE
Meta Changes Oct 2024

### ISSUE THREAD

**Issue by excentrickristy** [jakartaee/jakarta.ee#2017]
The following are some meta changes to help support the new Jakarta EE 11 release.

- [ ] https://jakarta.ee/specifications/data/
New Title: Jakarta Data Specification | Jakarta EE | The Eclipse Foundation
New Description: The Jakarta Data Specification defines core APIs for the Jakarta EE platform allowing applications and other Jakarta EE components to explore the benefits of easy access to data technologies such as relational and non-relational databases, cloud-based data services, and so on.
- [ ] https://jakarta.ee/specifications/data/1.0/
New Title: Jakarta Data 1.0 Specification | Jakarta EE | The Eclipse Foundation
New Description: The Jakarta Data specification provides an API for easier data access. A Java developer can split the persistence from the model with several features, such as the ability to compose custom query methods on a Repository interface.
- [ ] https://jakarta.ee/specifications/cdi/
New Title: Jakarta Contexts and Dependency Injection (CDI) Specification | Jakarta EE | The Eclipse Foundation
New Description: The Jakarta Contexts and Dependency Injection (CDI) Specification defines a powerful set of complementary services that help to improve the structure of application code.
- [ ] https://jakarta.ee/specifications/cdi/4.1/
New Title: Jakarta Contexts and Dependency Injection (CDI) 4.1 Specification | Jakarta EE | The Eclipse Foundation
New Description: Jakarta Contexts Dependency Injection (CDI) 4.1 for Jakarta EE 11 specifies a means for obtaining objects in such a way as to maximize reusability, testability and maintainability compared to traditional approaches such as constructors, factories, and service locators (e.g., JNDI).
- [ ] https://jakarta.ee/learn/starter-guides/
New Title: Jakarta EE Starter Guides | Get Started with Jakarta EE | Jakarta EE | The Eclipse Foundation

**Comment by oliviergoulet5** [comment]
@excentrickristy I have a preview for the starter guides page:

https://deploy-preview-2018--jakartaee.netlify.app/learn/starter-guides/

I will need to make a separate patch and preview for the specification pages since those pages live in a different repository.

**Comment by oliviergoulet5** [comment]
@excentrickristy Are we only changing the meta description for the specification pages? Or are we also updating the summaries which appear on the page?

![image](https://github.com/user-attachments/assets/8650b21a-a517-4813-9a00-9c9476ae81a6)

**Comment by excentrickristy** [comment]
We are only changing the meta descriptions!

**Comment by excentrickristy** [comment]
> @excentrickristy I have a preview for the starter guides page:
> 
> https://deploy-preview-2018--jakartaee.netlify.app/learn/starter-guides/
> 
> I will need to make a separate patch and preview for the specification pages since those pages live in a different repository.

This looks good!

**Comment by ericpoirier** [comment]
The updates are on production. 

Please reopen if we are missing something.
