### ISSUE TITLE
Translate the website in Chinese

### ISSUE THREAD

**Issue by chrisguindon** [jakartaee/jakarta.ee#866]
We would like to translate jakarta.ee in China. 

**Stage 1**
- [x] Translate the hugo-solstice-theme: https://github.com/jakartaeechina/website/blob/src/themes/default/i18n/cn.toml
- [x] Add language switcher and translate config.toml https://github.com/jakartaeechina/website/blob/src/config.toml
- [x] Start translating content such as homepage and about. (We need to define which page we need to translate).

**Stage 2**
- [ ] Create new /jakartaeechina/ section to host unique pages for the Chinese community.

**Comment by laliwa** [comment]
already pull request these steps
* [x]Translate the hugo-solstice-theme: https://github.com/jakartaeechina/website/blob/src/themes/default/i18n/cn.toml
https://github.com/EclipseFdn/hugo-solstice-theme/pull/153
* [x]Add language switcher and translate config.toml https://github.com/jakartaeechina/website/blob/src/config.toml
https://github.com/jakartaee/jakarta.ee/pull/867

**Comment by flora8984461** [comment]
Is this link https://github.com/jakartaeechina/website/blob/src/themes/default/i18n/cn.toml  still available? @chrisguindon

**Comment by autumnfound** [comment]
> Is this link https://github.com/jakartaeechina/website/blob/src/themes/default/i18n/cn.toml still available? @chrisguindon

See the link underneath that bullet (#867). The Chinese translations have been migrated here and are in the process of being reviewed!

**Comment by chrisguindon** [comment]
@autumnfound I took a look at the issue and there are more than 5000 files that are changing.

I don't think the issue is ready to be reviewed at the moment.

**Comment by chrisguindon** [comment]
For those who are watching this issue, a preview of the translation is available here:
https://deploy-preview-888--jakartaee.netlify.app/zh/

**Comment by chrisguindon** [comment]
@flora8984461 can you review the content to make sure it's aligned with the English version of the site?

**Comment by chrisguindon** [comment]
Quick update:

I've ask @TanjaObradovic and @shabnammayel to share this update with the Marketing committee! We need them to approve this change before I can merge this to production!

**Comment by TanjaObradovic** [comment]
@chrisguindon - I will send a note to all Jakarta EE committees and ask them for input (if any) by the end of this week.

@laliwa are we going to add Jakarta EE Community China specific pages at the later date?

**Comment by edbratt** [comment]
Is it possible to detect or manually complete links so they resolve to English pages wherever that page content is not translated?

**Comment by laliwa** [comment]
> @chrisguindon - I will send a note to all Jakarta EE committees and ask them for input (if any) by the end of this week.
> 
> @laliwa are we going to add Jakarta EE Community China specific pages at the later date?

Sure, there is already a page locally on my laptop. Just to introduce the Jakarta EE Community China, and accept sign up for participanting in the community by signing form just like what jakartaee-ambassodors do.  and I will also add the link for someone who want to subscribe the mailing list as well.

**Comment by flora8984461** [comment]
The translation is good, just a question regarding English page, 
Seems this English menu is missing a "documentation", which is the first section of this page.
![image](https://user-images.githubusercontent.com/39588094/93240393-0f0b5000-f752-11ea-9d55-b49cfe166505.png)

**Comment by autumnfound** [comment]
> The translation is good, just a question regarding English page,
> Seems this English menu is missing a "documentation", which is the first section of this page.
> ![image](https://user-images.githubusercontent.com/39588094/93240393-0f0b5000-f752-11ea-9d55-b49cfe166505.png)

I looked into this, it looks like an issue with the English sitemap, not caused by this upgrade. We can create a bug to fix this! @laliwa don't worry about this one at least! :)

**Comment by laliwa** [comment]
> > The translation is good, just a question regarding English page,
> > Seems this English menu is missing a "documentation", which is the first section of this page.
> > ![image](https://user-images.githubusercontent.com/39588094/93240393-0f0b5000-f752-11ea-9d55-b49cfe166505.png)
> 
> I looked into this, it looks like an issue with the English sitemap, not caused by this upgrade. We can create a bug to fix this! @laliwa don't worry about this one at least! :)

sorry I'm late to see this, and I have already pushed a commit by fixing the config.toml file. should I revert it or something? @autumnfound

**Comment by laliwa** [comment]
> > > > The translation is good, just a question regarding English page,
> > > > Seems this English menu is missing a "documentation", which is the first section of this page.
> > > > ![image](https://user-images.githubusercontent.com/39588094/93240393-0f0b5000-f752-11ea-9d55-b49cfe166505.png)
> > > 
> > > 
> > > I looked into this, it looks like an issue with the English sitemap, not caused by this upgrade. We can create a bug to fix this! @laliwa don't worry about this one at least! :)
> > 
> > 
> > sorry I'm late to see this, and I have already pushed a commit by fixing the config.toml file. should I revert it or something? @autumnfound
> 
> I fixed this since I'm already going to be poking in your branch, so don't worry about it!

Great!

**Comment by melissajacobus** [comment]
Primeton did a great work, translating the English version to the Chinese exactly. But some items are still in English. Please review the pages one by one and localize all the content. The links on the right side of the page still point to English pages. Please see the attached word document for specifics.
[Jakarta EE.docx](https://github.com/jakartaee/jakarta.ee/files/5240085/Jakarta.EE.docx)

**Comment by laliwa** [comment]
> Primeton did a great work, translating the English version to the Chinese exactly. But some items are still in English. Please review the pages one by one and localize all the content. The links on the right side of the page still point to English pages. Please see the attached word document for specifics.
> [Jakarta EE.docx](https://github.com/jakartaee/jakarta.ee/files/5240085/Jakarta.EE.docx)

Thanks a lot, Melissa, that really helps a lot! ^o^

**Comment by TanjaObradovic** [comment]
Per conversation we had on the Marketing Committee call focused on jakarta.ee Chinese translation, I have set up a meeting with our development team to address remaining questions 
- specification pages (404) (any page that is not translated should be by default shown in English)
- The very first specification page https://jakarta.ee/specifications/ could be translated - but Eric has questions.
- revisit all PRs / issues opened related to jakarta.ee translation ( #888)

**Comment by chrisguindon** [comment]
I will close this issue now that the translation is live. I would recommend that we create new issues for the next round of updates!
